# #   -5 -4 -3 -2 -1
# li=[1 , 2, 3, 4, [5,6,7]]
# #   0   1  2  3  4   
# print(-len(li))  # Output: -5
# print(len(li))   # Output: 5
# print(len(li)//2)  # Output: 2



# hi=((-len(li))**2)//2
# print(hi)  # Output: 12
# li=[12,23,[45,65,85],6,25]




# h="python"
# h1='python'
# h2="""python"""
# h3='''python'''

# gokul = ''
# # Strings in Python are immutable, so you cannot modify them in place.
# # To "modify" a string, you must create a new string.
# # Example: adding text to the string
# gokul = gokul + 'hello'
# print(gokul)  # Output: hello

# a = [gokul]


# a=input()
# print(a[::-1])



# n=5 

# for i in range(n+1):
#     print(end=" ")
#     for j in range(i):
#         print("3",end="")


# a=[1,1,2,2,3,4,5]
# b=[]
# for i in a:
#      if a.count(i) >1:
#          print(i)

# a=5000
# for i in range(a):
#     print(chr(i),end=" ")
    
# b=set(a)
# print(list(b))